### ISSUE TITLE
Datadog cluster agent in crashloopbackoff

### ISSUE THREAD

**Issue by ilbarone87** [DataDog/helm-charts#1181]
**Describe what happened:**
Since the update of the Helm Chart to 3.38.0 we've seen the datadog cluster agent pod in crash.
Restarting the pod doesn't fix the issue.
Looking at the logs we can see this.

```
2023-09-22 11:39:36 UTC | CLUSTER | INFO | (subcommands/start/command.go:408 in setupClusterCheck) | Started cluster check Autodiscovery
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2dd09bc]

goroutine 1 [running]:
github.com/DataDog/datadog-agent/pkg/clusteragent/admission/patch.StartControllers({0xc001d09010, 0xc001d09020, {0x45e7688, 0xc000af2d80}, 0x0, {0xc00007c0d0, 0xa}, {0xc0004c0b70, 0x24}, 0xc000bcc720})
        /go/src/github.com/DataDog/datadog-agent/pkg/clusteragent/admission/patch/start.go:32 +0x5c
github.com/DataDog/datadog-agent/cmd/cluster-agent/subcommands/start.start({0x45cef80, 0x64a4d68}, {0x45e08d0?, 0xc000bab158}, {0x45d2c90, 0xc000c46b90}, {0x45d6d70?, 0xc0001e7380}, 0x9?)
        /go/src/github.com/DataDog/datadog-agent/cmd/cluster-agent/subcommands/start/command.go:303 +0x15f8
reflect.Value.call({0x34b63e0?, 0x3bd57d8?, 0x10?}, {0x39ed093, 0x4}, {0xc0001e7480, 0x5, 0xc000e3f900?})
        /goroot/src/reflect/value.go:586 +0xb0b
reflect.Value.Call({0x34b63e0?, 0x3bd57d8?, 0xc000e3f968?}, {0xc0001e7480?, 0x0?, 0x0?})
        /goroot/src/reflect/value.go:370 +0xbc
github.com/DataDog/datadog-agent/pkg/util/fxutil.(*delayedFxInvocation).call(0xc000849450?)
        /go/src/github.com/DataDog/datadog-agent/pkg/util/fxutil/args.go:72 +0xc5
github.com/DataDog/datadog-agent/pkg/util/fxutil.OneShot({0x34b63e0?, 0x3bd57d8?}, {0xc0003ced20, 0x5, 0x5})
        /go/src/github.com/DataDog/datadog-agent/pkg/util/fxutil/oneshot.go:51 +0x1bf
github.com/DataDog/datadog-agent/cmd/cluster-agent/subcommands/start.Commands.func1(0xc000004900?, {0x39ed8db?, 0x0?, 0x0?})
        /go/src/github.com/DataDog/datadog-agent/cmd/cluster-agent/subcommands/start/command.go:77 +0x476
github.com/spf13/cobra.(*Command).execute(0xc000004900, {0x64a4d68, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004300)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0xc000e3fef0?)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
main.main()
        /go/src/github.com/DataDog/datadog-agent/cmd/cluster-agent/main.go:40 +0x15b
```

The cluster is running on bare metal linux VMs. it has 3 masters and 5 workers. Version v1.24.3

Reverting to 3.37.0 fixed the issue for now.

**Comment by L3n41c** [comment]
Hello !

Thank you for reporting this issue !

This is a bug in the cluster-agent that has been fixed by DataDog/datadog-agent#19596.
