### ISSUE TITLE
cluster-agent fails with initialisation errors (You have to define a namespace for each prometheus check)

### ISSUE THREAD

**Issue by safaa-alnabulsi** [DataDog/helm-charts#81]
**Describe what happened:**
I upgraded my cluster-agent-deployment.yaml deployment to work with k8s v1.16. 
Basically, I have a copy of https://www.datadoghq.com/blog/monitoring-kubernetes-with-datadog/ but with a custom different namespace.
All other parameters which were there didn't change. 

The pods are restarting and I get the following error:

```
kubectl exec -it datadog-datadog-8mv9w  -n monitoring -- agent status

      prometheus (3.3.0)
      ------------------

      instance 0:

        could not invoke 'prometheus' python check constructor. New constructor API returned:
__init__() takes at least 4 arguments (4 given)Deprecated constructor API returned:
Traceback (most recent call last):
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/prometheus/base_check.py", line 97, in __init__
    self.get_scraper(instance)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/prometheus/base_check.py", line 126, in get_scraper
    raise CheckException("You have to define a namespace for each prometheus check")
CheckException: You have to define a namespace for each prometheus check

  Config Errors
  ==============
    statsd_receiver
    ---------------
      Configuration file contains no valid instances

```

**Describe what you expected:**

As this part didn't change and there's nothing in the docs related to it, i expected it to work.
- DaemonSet datadog is already upgraded to work with v1.16.
- kube-state-metrics is already upgraded to work with v1.16.

**Steps to reproduce the issue:**

changed: apiVersion: 

`extensions/v1beta1 >> apiVersion: apps/v1
`
added:
```

  selector:
    matchLabels:
      app: kube-state-metrics
      release: datadog
  strategy:
    type: RollingUpdate

```

**Additional environment details (Operating System, Cloud provider, etc):**
AWS, EKS

I tried upgrading datadog-agent from 6.20.0 to 7.17.0 to 7.23.1, The error is still the same

**Comment by safaa-alnabulsi** [comment]
The issue was related to another controller which I fixed and started happening after the changes done in datadog.
